linked_field.config:
  type: config_object
  label: 'Linked field configuration'
  mapping:
    attributes:
      type: sequence
      label: 'Attributes'
      sequence:
        type: linked_field.label_description
        label: 'Attribute'

linked_field.label_description:
  type: mapping
  label: 'Label/description'
  mapping:
    label:
      type: string
      label: 'Label'
    description:
      type: string
      label: 'Description'

field.formatter.third_party.linked_field:
  type: linked_field.third_party_settings

linked_field.third_party_settings:
  type: mapping
  label: 'Linked field third party field settings'
  mapping:
    linked:
      type: boolean
      label: 'Is linked'
    type:
      type: string
      label: 'Type of linkage'
    destination:
      type: string
      label: 'Linked destination'
    advanced:
      type: sequence
      label: 'Advanced'
      sequence:
        type: string
        label: 'Attribute'
